apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
#  namespace: kafka
spec:
  type: LoadBalancer
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  - name: prometheus-0
    port: 9250
  - name: cassandra
    port: 9042
  - name: kafka
    port: 9092
  selector:
    app: flink
    component: jobmanager