apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
  labels:
    name: cassandra
spec:
  ports:
  - port: 9042
    name: cassandra-port
    protocol: TCP
  selector:
    app: cassandra
    type: nosql-db
  type: LoadBalancer
