apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
#  namespace: kafka
spec:
  type: LoadBalancer
  ports:
  - name: kafka-producer-port
    port: 7080
    protocol: TCP
  - name: kafka-producer-jmx-port
    port: 7085
    protocol: TCP 
  selector:
    app: kafka-producer