FROM flink:1.11.1-scala_2.12
WORKDIR /opt/flink/usrlib
COPY ./target/kafka-flink-consumer-cassandra-sink-0.0.1-SNAPSHOT.jar /opt/flink/usrlib/kafka-flink-consumer-cassandra-sink-0.0.1-SNAPSHOT.jar
#ADD /opt/flink/usrlib/kafka-flink-consumer-cassandra-sink-0.0.1-SNAPSHOT.jar /opt/flink/usrlib/kafka-flink-consumer-cassandra-sink-0.0.1-SNAPSHOT.jar